# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Zebra' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Zebra
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'

  pod 'Toast-Swift', '~> 2.0.0'
  pod 'ActionSheetPicker-3.0'
  pod 'LocationPicker'

end
